# Generated by Django 5.0.1 on 2024-04-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_general", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment",
            new_name="Register",
        ),
    ]
