# Generated by Django 5.0.1 on 2024-04-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_gamelist", "0002_game_initial_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
