# Generated by Django 5.0.1 on 2024-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_gamelist", "0003_game_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="image_relative_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
