# Generated by Django 5.0.1 on 2024-04-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_gamelist", "0004_game_image_relative_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="genre",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
